version: '3'

services:
    nginx:
        image: frontend-nginx:latest
        build:
            context: ${NGINX_CONTEXT_DIR}
            args:
                - NGINX_PORT=${NGINX_PORT}
        ports:
            - "${NGINX_PORT}:${NGINX_PORT}"
        networks:
            frontend:
                ipv4_address: ${FRONTEND_NGINX_IP}
        volumes:
        volumes:
            - "vol-log-nginx:/var/log/nginx"

    postgres:
        image: backend-postgres:latest
        build:
            context: ${POSTGRES_CONTEXT_DIR}
            args:
                - POSTGRES_PORT=${POSTGRES_PORT}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        networks:
            backend:
                ipv4_address: ${BACKEND_POSTGRES_IP}
        volumes:
            - "vol-pg-data:/var/lib/postgresql/data"
            - "vol-log-pg:/var/lib/postgresql/log"
    server-backend:
        image: backend-server:latest
        build: ${SERVER_CONTEXT_DIR}
        networks:
            backend:
                ipv4_address: ${BACKEND_SERVER_IP}
            frontend:
                ipv4_address: ${FRONTEND_SERVER_IP}
volumes:
    vol-pg-data:
    vol-log-pg:
    vol-log-nginx:

networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: ${BACKEND_SUBNET}
    frontend:
        ipam:
            driver: default
            config:
                - subnet: ${FRONTEND_SUBNET}
