version: '3'

services:
    nginx:
        image: frontend-nginx:latest
        build: test-elm/nginx/
        ports:
            - "80:80"
        networks:
            frontend:
                ipv4_address: "172.16.11.10"
        volumes:
        volumes:
            - "vol-log-nginx:/var/log/nginx"

    postgres:
        image: backend-postgres:latest
        build: test-backend/postgresql/
        ports:
            - "5432:5432"
        networks:
            backend:
                ipv4_address: "172.16.10.11"
        volumes:
            - "vol-pg-data:/var/lib/postgresql/data"
            - "vol-log-pg:/var/lib/postgresql/log"
    server:
        image: backend-server:latest
        build: test-backend/server/
        networks:
            backend:
                ipv4_address: "172.16.10.10"
            frontend:
                ipv4_address: "172.16.11.11"
volumes:
    vol-pg-data:
    vol-log-pg:
    vol-log-nginx:

networks:
    frontend:
        ipam:
            driver: default
            config:
                - subnet: "172.16.11.0/24"
    backend:
        ipam:
            driver: default
            config:
                - subnet: "172.16.10.0/24"
