version: '3'

services:
    nginx:
        image: frontend-nginx:latest
        build: test-elm/nginx/
        ports:
            - "80:80"
        volumes:
            - "vol-log-nginx:/var/log/nginx"

    postgres:
        image: backend-postgres:latest
        build: test-backend/postgresql/
        ports:
            - "5432:5432"
        volumes:
            - "vol-pg-data:/var/lib/postgresql/data"
            - "vol-log-pg:/var/lib/postgresql/log"
    server:
        image: backend-server:latest
        build: test-backend/server/
        ports:
            - "10001:10001"
volumes:
    vol-pg-data:
    vol-log-pg:
    vol-log-nginx:
